### PR TITLE
[Bugfix] check nil before dereferencing

### LINKED ISSUE #704: [BUG] events: nil pointer dereference
**Describe the bug**

In smart contracts if the developer uses `Event::new("")` without an attribute the node will panic (recoverable) due to a nil pointer dereference. 

https://github.com/terra-money/core/blame/main/x/wasm/types/connector.go#L39
https://github.com/terra-money/core/blame/main/x/wasm/types/connector.go#L49

**To Reproduce**

Deploy a smart contract to bombay-12 with `Ok(Response::new().add_event(Event::new("something"))` or `Ok(Response::default().add_event(Event::new("something")))` and then when you call the message it will panic with a nil pointer dereference. 

**Context & versions**
latest
tested on bombay-12

**(if applicable) suggested solution**

check if attributes are nil before dereferencing

### PR DESCRIPTION
**Pull request by YunSuk-Yeo**
## Summary of changes

close #704 

## Report of required housekeeping

- [ ] Github issue OR spec proposal link
- [ ] Wrote tests
- [ ] Updated API documentation (client/lcd/swagger-ui/swagger.yaml)
- [ ] Added a relevant changelog entry: clog add [section] [stanza] [message]

----

## (FOR ADMIN) Before merging

- [ ] Added appropriate labels to PR
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" (coding standards)
- [ ] Confirm added tests are consistent with the intended behavior of changes
- [ ] Ensure all tests pass

### CODE REVIEW

**Review by hanjukim — APPROVED** [review]

File: x/wasm/types/connector.go [hunk 1]
```diff
@@ -36,7 +36,9 @@ func ParseEvents(
 
 		// Deprecated: from_contract
 		sdkEvent.Type = EventTypeFromContract
-		sdkEvents = sdkEvents.AppendEvent(*sdkEvent)
+		if sdkEvent != nil {
```
Comment (peterbourgon) [inline x/wasm/types/connector.go:39]: If sdkEvent is nil, this code will panic on lines 35 and 38, before it gets here. The problem is that buildEvent can return a nil *sdk.Event _and_ a nil error. That should not happen. Either have buildEvent return an error if len(attributes) == 0, or check len(attributes) before calling buildEvent.

Comment (amazingandyyy) [reply x/wasm/types/connector.go:39]: + in line 29, len(attributes) is checked
